//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Assets1 = new HashSet<Asset>();
            this.JobAssets = new HashSet<JobAsset>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string ClientRef { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string SerialNo { get; set; }
        public string SSN { get; set; }
        public string Barcode { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> WMSItemType_ID { get; set; }
        public Nullable<decimal> WMSWarehouse_ID { get; set; }
        public bool IsSelected { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomField6 { get; set; }
        public string CustomField7 { get; set; }
        public string CustomField8 { get; set; }
        public string CustomField9 { get; set; }
        public string CustomField10 { get; set; }
        public string AssetID { get; set; }
        public bool IsSerialised { get; set; }
        public string SKUCode { get; set; }
        public int QtyOnHand { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public string Condition { get; set; }
        public string ScreenSize { get; set; }
        public bool IsScanned { get; set; }
        public string AssetTag { get; set; }
        public string UserID { get; set; }
        public string DeskNumber { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string PalletNo { get; set; }
        public string ReservationCustomer { get; set; }
        public string ReservationComment { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public Nullable<System.DateTime> GRADate { get; set; }
        public Nullable<double> DV { get; set; }
        public string Grade { get; set; }
        public bool IsScrap { get; set; }
        public Nullable<System.DateTime> DateTested { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> ReportId { get; set; }
        public string FormattedCondition { get; set; }
        public string Completeness { get; set; }
        public string Appearance { get; set; }
        public string Services { get; set; }
        public string Operability { get; set; }
        public Nullable<System.DateTime> ConditionReportDate { get; set; }
        public Nullable<System.DateTime> PhysicalInspectionDate { get; set; }
        public string PhysicalInspectionUser { get; set; }
        public Nullable<int> ConditionCount { get; set; }
        public Nullable<decimal> ExpectedSellPrice { get; set; }
        public Nullable<System.DateTime> DateBilled { get; set; }
        public Nullable<System.DateTime> DateRemitted { get; set; }
        public string ClientAssetTag { get; set; }
        public Nullable<int> Asset_Asset2 { get; set; }
        public int Asset_AssetStatus { get; set; }
        public Nullable<int> Asset_AssetType { get; set; }
        public Nullable<int> Asset_Bin { get; set; }
        public Nullable<int> Asset_Brand1 { get; set; }
        public Nullable<int> Asset_Dispatch1 { get; set; }
        public Nullable<int> Asset_ItemType1 { get; set; }
        public Nullable<int> Asset_JobBundle { get; set; }
        public Nullable<int> Asset_Job1 { get; set; }
        public Nullable<int> Asset_Load2 { get; set; }
        public Nullable<int> Asset_Model1 { get; set; }
        public Nullable<int> Asset_StockCategory { get; set; }
        public int Asset_Project { get; set; }
        public Nullable<int> Asset_ReservationCode { get; set; }
        public Nullable<int> Asset_StockCategory1 { get; set; }
        public Nullable<int> Asset_Warehouse { get; set; }
        public string OldSSN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets1 { get; set; }
        public virtual Asset Asset1 { get; set; }
        public virtual AssetStatusSet AssetStatusSet { get; set; }
        public virtual Bin Bin { get; set; }
        public virtual Brand Brand1 { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual Job Job { get; set; }
        public virtual Load Load { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAsset> JobAssets { get; set; }
    }
}
