//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bundle
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string BundleType { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string FriendlyDescription { get; set; }
        public bool IsInactive { get; set; }
        public Nullable<decimal> WMSSiteWarehouse_ID { get; set; }
        public string WMSInventory_Inventory { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<int> Bundle_AssetStatus { get; set; }
        public Nullable<int> Bundle_Inventory { get; set; }
        public int ServiceBundle_Project { get; set; }
        public Nullable<int> Bundle_Site { get; set; }
        public Nullable<int> Bundle_Warehouse1 { get; set; }
        public Nullable<int> ServiceBundle_Zone { get; set; }
    
        public virtual AssetStatusSet AssetStatusSet { get; set; }
        public virtual Project Project { get; set; }
    }
}
