//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JMSEntities : DbContext
    {
        public JMSEntities()
            : base("name=JMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asset> Assets { get; set; }
        public virtual DbSet<AssetStatusSet> AssetStatusSets { get; set; }
        public virtual DbSet<Bin> Bins { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Bundle> Bundles { get; set; }
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<Colour> Colours { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Connector> Connectors { get; set; }
        public virtual DbSet<CPU> CPUs { get; set; }
        public virtual DbSet<CPUSpeed> CPUSpeeds { get; set; }
        public virtual DbSet<ItemType> ItemTypes { get; set; }
        public virtual DbSet<JobAsset> JobAssets { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Load> Loads { get; set; }
        public virtual DbSet<MCQ_MobileAssetsFeed> MCQ_MobileAssetsFeed { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
    }
}
