//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Assets = new HashSet<Asset>();
            this.JobAssets = new HashSet<JobAsset>();
            this.Loads = new HashSet<Load>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string JobNo { get; set; }
        public string JobType { get; set; }
        public string ClientRef { get; set; }
        public string ClientPO { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<System.DateTime> SLA { get; set; }
        public System.DateTime JobDate { get; set; }
        public Nullable<System.DateTime> JobTime { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string WorkInstructions { get; set; }
        public string Department { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string RunNo { get; set; }
        public string ContactPerson { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> BundleTotal { get; set; }
        public Nullable<decimal> AssetPurchaseTotal { get; set; }
        public string InvoiceNotes { get; set; }
        public bool IsSelected { get; set; }
        public bool IsInactive { get; set; }
        public int MYOBCostCentre_CostCentreID { get; set; }
        public int MYOBEmployee_EmployeeID { get; set; }
        public Nullable<int> MYOBSale_SaleID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<int> MYOBCustomer_CustomerID { get; set; }
        public string CustomerSignatureVector { get; set; }
        public byte[] CustomerSignatureImage { get; set; }
        public string TechnicianSignatureVector { get; set; }
        public byte[] TechnicianSignatureImage { get; set; }
        public string WorkOrderUrl { get; set; }
        public string IncomingFreightProvider { get; set; }
        public string IncomingConsignmentNo { get; set; }
        public string IncomingStatus { get; set; }
        public Nullable<System.DateTime> IncomingDateReceived { get; set; }
        public string IncomingReceiverName { get; set; }
        public string OutgoingFreightProvider { get; set; }
        public string OutgoingConsignmentNo { get; set; }
        public string OutgoingStatus { get; set; }
        public Nullable<System.DateTime> OutgoingDateReceived { get; set; }
        public string OutgoingReceiverName { get; set; }
        public Nullable<System.DateTime> PostJobSLA { get; set; }
        public string InternalComments { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> JobMonth { get; set; }
        public Nullable<int> JobYear { get; set; }
        public string TechnicianName { get; set; }
        public string CustomerName { get; set; }
        public bool WorkOrderExported { get; set; }
        public Nullable<System.DateTime> DateSigned { get; set; }
        public string DellType { get; set; }
        public bool IsChecked { get; set; }
        public bool Checked { get; set; }
        public string OrderComments { get; set; }
        public bool SendMail { get; set; }
        public Nullable<bool> IsInvoicedOrCancelled { get; set; }
        public string Severity { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string OpportunityNumber { get; set; }
        public bool ApprovedForPicking { get; set; }
        public bool ApprovedForPacking { get; set; }
        public Nullable<System.DateTime> PickByDate { get; set; }
        public bool IsExport { get; set; }
        public string Currency { get; set; }
        public string OrderNo { get; set; }
        public string OrderSource { get; set; }
        public bool IsReadyToInvoice { get; set; }
        public bool PaymentReceived { get; set; }
        public Nullable<int> Job_ActivityType { get; set; }
        public Nullable<int> Job_Invoice { get; set; }
        public int Job_JobStatus { get; set; }
        public Nullable<int> Job_ProjectInventory { get; set; }
        public int Job_Project { get; set; }
        public Nullable<int> Job_Site { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAsset> JobAssets { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load> Loads { get; set; }
    }
}
