//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobAsset
    {
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string Comments { get; set; }
        public string OldSerialNumber { get; set; }
        public Nullable<bool> IsDoneTech { get; set; }
        public Nullable<bool> IsDoneUser { get; set; }
        public bool IsSelected { get; set; }
        public int JobAsset_Asset { get; set; }
        public Nullable<int> JobAsset_Dispatch { get; set; }
        public Nullable<int> JobAsset_JobBundle { get; set; }
        public int JobAsset_Job { get; set; }
        public string JObTest { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Job Job { get; set; }
    }
}
