//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Load()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public int Id { get; set; }
        public string LoadNo { get; set; }
        public System.DateTime DateReceived { get; set; }
        public string Connote { get; set; }
        public string ReceivingUser { get; set; }
        public string LoadStatus { get; set; }
        public Nullable<System.DateTime> GRADate { get; set; }
        public Nullable<decimal> LoadTotal { get; set; }
        public string ReferenceNumber { get; set; }
        public string Comments { get; set; }
        public Nullable<int> EstimatedQty { get; set; }
        public Nullable<int> ActualQty { get; set; }
        public Nullable<System.DateTime> UNGRADate { get; set; }
        public string UNGRAReason { get; set; }
        public string UNGRAUser { get; set; }
        public Nullable<int> LoadSLA { get; set; }
        public string OutOfSLA { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<System.DateTime> DateUploadedToDocsOnline { get; set; }
        public string GRAPath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTimeOffset> Modified { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> Load_Inventory3 { get; set; }
        public Nullable<int> Load_Job { get; set; }
        public Nullable<int> Load_LeaseCustomer { get; set; }
        public Nullable<int> Load_ProjectInventory { get; set; }
        public int Load_Project { get; set; }
        public Nullable<int> Load_Warehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Job Job { get; set; }
        public virtual Project Project { get; set; }
    }
}
