//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCQ_MobileAssetsFeed
    {
        public int ID { get; set; }
        public Nullable<int> AssetNumber { get; set; }
        public Nullable<int> MCQ_ID { get; set; }
        public Nullable<System.DateTime> Customer_Contract_Start_Date { get; set; }
        public Nullable<int> ServiceNumber { get; set; }
        public string Swap_Assure_Eligible { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string IMEI { get; set; }
        public string SSN { get; set; }
        public Nullable<int> reportId { get; set; }
    }
}
