//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCQFeedImport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Assets = new HashSet<Asset>();
            this.Bundles = new HashSet<Bundle>();
            this.Jobs = new HashSet<Job>();
            this.Loads = new HashSet<Load>();
        }
    
        public int Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string ProjectType { get; set; }
        public byte[] Logo { get; set; }
        public string WelcomeMessage { get; set; }
        public string CustomerPO { get; set; }
        public string BillingType { get; set; }
        public string Summary { get; set; }
        public string UrlSegment { get; set; }
        public string Login { get; set; }
        public bool IsInactive { get; set; }
        public int MYOBCostCentre_CostCentreID { get; set; }
        public int MYOBEmployee_EmployeeID { get; set; }
        public int MYOBEmployee_EmployeeID1 { get; set; }
        public Nullable<int> MYOBSale_SaleID { get; set; }
        public Nullable<int> MYOBJob_JobID { get; set; }
        public Nullable<int> MYOBSupplier_SupplierID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string LastUpdateUser { get; set; }
        public string DocsOnlineFolder { get; set; }
        public bool UseNetInvoicing { get; set; }
        public bool IncludeClientRefInCafFilename { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public bool SendJobStatusUpdate { get; set; }
        public string ClientReference { get; set; }
        public bool IncludeClientReferenceInJobCompletionEmail { get; set; }
        public bool SendLoadEmailNotification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bundle> Bundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Load> Loads { get; set; }
    }
}
